name: AutoPrompt

channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - pip>=2.22.0
  - openai
  - anthropic
  - langchain
  - pandas
  - wandb
  - transformers
  - tqdm
  - faiss-cpu
  - sentence-transformers
  - pip:
      - prodict
      - argilla==1.25.0
      - schedule
      - pandas
      - easydict
      - pillow==10.2.0

     models:
  - name: ChuanhuChatGPT
    provider: chuanhu
    category: AI Chatbot
    license: MIT
    origin: code
    homepage: https://github.com/GaiZhenbiao/ChuanhuChatGPT
    vulnerabilities:
      - CVE-2024-5982
      - CVE-2024-7473

  - name: LocalAI
    provider: localai
    category: AI Platform
    license: Apache-2.0
    origin: code
    homepage: https://github.com/go-skynet/LocalAI
    vulnerabilities:
      - CVE-2024-6983
      - CVE-2024-7010

  - name: Deep Java Library (DJL)
    provider: djl
    category: AI Library
    license: Apache-2.0
    origin: code
    homepage: https://github.com/deepjavalibrary/djl
    vulnerabilities:
      - CVE-2024-8396

