# Initialize client with API key
client = InferenceClient(api_key="***", model="mkiani/gpt2-system", task="text-generation")

# Generate response
response = client.text_generation("What is machine learning?")
print(response)
