# Name of your GitHub Actions Workflow
name: Mend Security Scan 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mend-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step will now succeed because pom.xml exists in the repo
      - name: Set up JDK 17 and Cache Maven Dependencies
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # This line caused the error, but will work now

      - name: Build Project & Install Dependencies
        run: |
          # This debug step will now show pom.xml in the list
          echo "--- Listing files in workspace ---"
          ls -la
          
          echo "--- Building project with Maven ---"
          mvn -B clean dependency:resolve compile -f pom.xml

      - name: Download Mend CLI
        run: |
          curl -L -o mend https://downloads.mend.io/cli/linux_amd64/mend
          chmod +x mend
      
      - name: Run Mend Scans and Generate Report
        env:
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          MEND_EMAIL: ${{ vars.ENVEMAIL }}
          MEND_URL: https://saas-eu.mend.io
        run: |
          MEND_SCOPE="product=My_Web_Applications -project=WebGoat_Main_Branch"
          ./mend deps --scope "$MEND_SCOPE" --reachability
          ./mend code --scope "$MEND_SCOPE"
          sleep 30
          ./mend deps --scope "$MEND_SCOPE" --export-results sca-report.json

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-scan-report
          path: sca-report.json
